import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import Rentify from "@/components/ui/Rentify";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
          <head />
          <body className="antialiased">
            <Provider>{children}</Provider>
            <Toaster />
            <Rentify />
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
